- hosts: fortigates
  connection: httpapi

  # when using the colltion
  #collections:
  #- fortinet.fortios
  gather_facts: false
  vars_files:
    - vars.yml


  tasks:
  
  
  # - name: Configure MAC address tables.
  #   fortios_system_mac_address_table:
  #     host:  "{{ host }}"
  #     username: "{{ username }}"
  #     password: "{{ password }}"
  #     vdom:  "{{ vdom }}"
  #     https: "False"
  #     state: "present"
  #     system_mac_address_table:
  #       interface: "<your_own_value> (source system.interface.name)"
  #       mac: "<your_own_value>"
  #       reply_substitute: "<your_own_value>"

  - name: Configure DHCP server
    fortios_system_dhcp_server:
      vdom:  "{{ vdom }}"
      state: "present"
      system_dhcp_server:
        id: 1
        interface: "lan"
        reserved_address:
         -
            action: "reserved"
            id: 1
            ip: "192.168.1.50"
            mac: "11:22:33:44:f4:75"
            description: "Phone"
         -
            action: "reserved"
            id: 2
            ip: "192.168.1.5"
            mac: "11:22:33:44:3c:43"
            description: "example2"
 
    tags: [never, dhcp]

 
  - name: Configure DHCP server for wan
    fortios_system_dhcp_server:
      vdom:  "{{ vdom }}"
      state: "present"
      system_dhcp_server:
        #dns_server1: "8.8.8.8"
        id:  "20"
        interface: "wan2"
        ip_mode: "range"
        ip_range:
          -
            id:  "1"
            start_ip: "1.2.3.5"
            end_ip: "1.2.3.100"
            
        #server_type: "regular"
        #status: "disable"
        netmask: "255.255.255.0"
    tags: [never]

  - name: Configure DHCP server for lan
    fortios_system_dhcp_server:
      vdom:  "{{ vdom }}"
      state: "present"
      system_dhcp_server:        
        id:  "10"
        interface: "lan"
        default_gateway: "192.168.1.1"
        netmask: "255.255.255.0"
        ip_mode: "range"
        ip_range:
          -
            id:  "1"
            start_ip: "192.168.1.10"
            end_ip: "192.168.1.200"
            
        #server_type: "regular"
        status: "enable"
        dns_service: specify
        dns_server1: "192.168.1.5"
        reserved_address:
          -
            action: "reserved"
            id: 1
            ip: "192.168.1.22"
            mac: "00:00:00:00:00:3c"
            description: "3c host"
          -
            action: "reserved"
            id: 2
            ip: "192.168.1.23"
            mac: "00:00:00:00:00:23"
            description: "3c host 2"

    tags: [never, dhcplan]

  - name: Delete DHCP server 20
    fortios_system_dhcp_server:
      vdom:  "{{ vdom }}"
      state: "absent"
      system_dhcp_server:
        #dns_server1: "8.8.8.8"
        id:  "20"
 
    tags: [never, dhcp20]
